project:
  type: website

website:
  title: "Statistica 2025"
  navbar:
    left:
      - href: index.qmd
        text: Home
#      - about.qmd

format:
  html:
    theme: flatly
    css: style.css
    toc: true
    toc-depth: 3
    toc-location: left




